name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma client for tests
      run: npx prisma generate --schema=prisma/schema.test.prisma
      env:
        DATABASE_URL: file:./test.db
        
    - name: Run tests
      run: npm test
      env:
        CI: true
        DATABASE_URL: file:./test.db
        TEST_DATABASE_URL: file:./test.db
        DISCORD_CLIENT_ID: test_client_id
        DISCORD_CLIENT_SECRET: test_client_secret
        DISCORD_CALLBACK_URL: http://localhost:3002/auth/discord/callback
        SESSION_SECRET: test_session_secret
        NODE_ENV: test
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results.json