name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: dismodular_test
          POSTGRES_USER: dismodular
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup test environment
      run: |
        echo "DATABASE_URL=postgresql://dismodular:password@localhost:5432/dismodular_test" >> $GITHUB_ENV
        echo "TEST_DATABASE_URL=postgresql://dismodular:password@localhost:5432/dismodular_test" >> $GITHUB_ENV
        echo "DISCORD_CALLBACK_URL=http://localhost:3002/auth/discord/callback" >> $GITHUB_ENV
        echo "DISCORD_CLIENT_ID=test_client_id" >> $GITHUB_ENV
        echo "DISCORD_CLIENT_SECRET=test_client_secret" >> $GITHUB_ENV
        echo "DISCORD_BOT_TOKEN=test_bot_token" >> $GITHUB_ENV
        echo "INITIAL_ADMIN_DISCORD_ID=189921902553202688" >> $GITHUB_ENV
        echo "SESSION_SECRET=test_session_secret" >> $GITHUB_ENV
        echo "NODE_ENV=test" >> $GITHUB_ENV
    
    - name: Generate Prisma Client
      run: npx prisma generate
    
    - name: Run database migrations
      run: npx prisma migrate deploy
      env:
        DATABASE_URL: postgresql://dismodular:password@localhost:5432/dismodular_test
    
    - name: Run tests
      run: npm test
      env:
        DATABASE_URL: postgresql://dismodular:password@localhost:5432/dismodular_test
        TEST_DATABASE_URL: postgresql://dismodular:password@localhost:5432/dismodular_test
        DISCORD_CALLBACK_URL: http://localhost:3002/auth/discord/callback
        DISCORD_CLIENT_ID: test_client_id
        DISCORD_CLIENT_SECRET: test_client_secret
        DISCORD_BOT_TOKEN: test_bot_token
        INITIAL_ADMIN_DISCORD_ID: 189921902553202688
        SESSION_SECRET: test_session_secret
        NODE_ENV: test

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build dashboard
      run: npm run build --workspace=@dismodular/dashboard
    
    - name: Generate Prisma Client
      run: npx prisma generate
    
    - name: Check build artifacts
      run: |
        ls -la packages/dashboard/dist/
        test -f packages/dashboard/dist/index.html